sonar.projectKey=khanhcr123456_Pet_Care
sonar.organization=khanhcr123456

# Thư mục chứa mã nguồn cần scan (đối với Flutter/Dart)
sonar.sources=lib

# Loại bỏ các file generated không cần thiết
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,lib/generated_plugin_registrant.dart

# Cấu hình encoding
sonar.sourceEncoding=UTF-8